CREATE OR REPLACE TRIGGER CheckCustomerWealth
BEFORE INSERT OR UPDATE ON TRANS
FOR EACH ROW
DECLARE
    l_state CHAR;
BEGIN

    SELECT STATE 
    INTO l_state 
    FROM CUSTOMER 
    WHERE CUSTOMERID = :NEW.CUSTOMERID;
    
    IF l_state = 'WA' AND :NEW.SALESPRIcE < 1000 THEN

        RAISE_APPLICATION_ERROR(-20001, 'Pay less');
    ELSIF l_state = 'GA' AND :NEW.SALESPRIcE > 800 THEN

        RAISE_APPLICATION_ERROR(-20002, 'Pay more');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'Customer state not found.');
    WHEN OTHERS THEN
        RAISE;
END CheckCustomerWealth;
/

UPDATE TRANS
SET SALESPRICE = 801
WHERE TRANSCATIONID = (SELECT TRANS_ID FROM TRANS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE STATE = 'GA') AND ROWNUM = 1);

SELECT * FROM TRANS; 
SELECT * FROM CUSTOMER;
